import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrapper div to handle layout */}
        <div className="flex flex-col min-h-screen">
          {/* Header and Navbar */}
          <main>
            <Header />
          </main>
          <main>
            <Navbar />
          </main>
          {/* Main content (fills available space) */}
          <main className="flex-grow">{children}</main>
          {/* Footer at the bottom */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
